### ISSUE TITLE
Unnecessary formsettings.json created

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#14]

**Comment by HellUnit** [comment]
Did you want it to not create the file at all? For that, we can just comment out all the stuff in the FormClosing event. I was looking more into actually having it write the PactherForm.CurrentSettings into it, but my understanding of C Sharp property getters and setters is obviously lacking since I can't figure out how to access
```
public PatcherFormSettings CurrentSettings { get; set; }
```
from the ProjectSettingsControl Form. I was going to have it set CurrentSettings in the ProjectSettingsControl Form and when a new project is opened so that meaningful settings could be saved into formsettings.json during the FormClosing event and then reloaded when it opens.

**Comment by lukespragg** [comment]
I don't see a need for FormSettings, so I don't see why we shouldn't remove it.

**Comment by HellUnit** [comment]
Will do.
