### ISSUE TITLE
"Close Tab" only closes focused tab

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#59]
I'm not sure how easy this one is, but we'll see! Basically I am used to seeing programs where you can right click on any tab, and close it regardless of if it is focused or not. Chrome is a good example of this.

**Comment by HellUnit** [comment]
As a side note, right-clicking a tab now automatically focuses it. It was easier to do it this way, especially with the addition of the 'Close Other Tabs' Option since it closes all tabs that are not focused. Also, the right-click menu will now only show when the 'tab' at the top is right-clicked rather than anywhere in the tab. This has to do with changing it from a context menu as a property of the tabview object to a context menu is the mouse event handler for the tabview.

**Comment by HellUnit** [comment]
Actually, I've got an idea on how to get this to work without changing the 
selected tab. Gonna have a look-see in a bit.

Sent with AquaMail for Android
http://www.aqua-mail.com
