### ISSUE TITLE
Add command-line support to run without GUI

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#8]
This is useful for automated patching and builds.

**Comment by HellUnit** [comment]
I was looking into this and it seems that programs need to be declared as either GUI or Console since the kernel initializes each type differently. It is possible to have a WinForm application execute as a console application, but it requires some 'hacks' for lack of a better term. I think it would be easier to have a separate executable, say OxidePatcher_CLI.exe included in the project that could perform auto-patching functions when provided with the opj file. Something like "OxidePatcher_CLI.exe RustExperimental.opj Oxide.Core.dll" (it would take the path to the project file and path to Oxide.Core.dll as arguments). Thoughts?

**Comment by lukespragg** [comment]
The program should be able to detect if run from a command-line or opened from the desktop, but maybe. Pretty sure I've seen that done before, the detection that is.

**Comment by HellUnit** [comment]
I'm toying around with this at the moment.
```
namespace OxidePatcher
{
    static class Program
    {
        // defines for commandline output
        [DllImport("kernel32.dll")]
        static extern bool AttachConsole(int dwProcessId);
        private const int ATTACH_PARENT_PROCESS = -1;

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main(string[] args)
        {
            // redirect console output to parent process;
            // must be before any calls to Console.WriteLine()
            AttachConsole(ATTACH_PARENT_PROCESS);

            if (args.Length == 0)
            {
                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                Application.Run(new PatcherForm());
            }
            else if (args.Length == 2)
            {
                Project PatchProject = Project.Load(args[0]);
                Patcher patcher = new Patcher(PatchProject);
            }
            else
            {
                Console.WriteLine("SYNTAX: 'OxidePatcher.exe <PATH TO OPJ FILE> <PATH TO Oxide.Core.dll>'");
            }
        }
    }
}
```

**Comment by lukespragg** [comment]
I wouldn't stress TOO much over this issue though, as updates are usually still manual due to hooks being flagged from changes.

**Comment by HellUnit** [comment]
Got it done. It uses OxidePatcher.exe and takes the path to the project file as its only argument. If no arguments are given, it runs as a GUI. The path to Oxide.Core.dll is hardcoded in Patcher.cs to be next to OxidePatcher.exe, but that can be changed too if you think its necessary. All it does is automatically patch using the settings in the opj file. If hooks are flagged, they are skipped etc. It prints all the same messages to the console that it normally does in PatchProcessForm. I'll PR it if you're interested.

**Comment by lukespragg** [comment]
Sounds fine to me!

**Comment by HellUnit** [comment]
Yeah, it prints all that stuff to the console. Exact same output as in the PatchProcess Form. Only caveat seems to be, it won't exit when its done. You have to Ctrl-C it to regain control of the console. I tried System.Environment.Exit() and System.Application.Exit() and neither have any effect. I even tried System.Environment.FailFast() which pops up the error dialog saying the program failed and clicking 'Close Application' still doesn't return to the console. :-/

**Comment by generationtech** [comment]
Apologies in advance for commenting on old'ish closed issue, but was the "press enter to continue" problem ever addressed?

Without that, it's making automatic patching difficult because of user interaction

**Comment by lukespragg** [comment]
As far as a I know, there's no issue with automatic patching, though I would discourage blindly patching @generationtech.

**Comment by generationtech** [comment]
When run as a command line utility with -c and *.opj file, it stops with "press enter to continue"

I've commented out that Console.WriteLine line and it still happens (of course).
When I commented out the single. patcher.Patch() just above, it returns to command line after execution (without patching of course).

Something in the OxidePatcher code causes it command line version to not exist and return to command prompt.

Thanks for any help.

**Comment by HellUnit** [comment]
On July 6, 2017 3:53:40 PM EDT, Ken McDonald <notifications@github.com> wrote:
>When run as a command line utility with -c and *.opj file, it stops
>with "press enter to continue"
>
>I've commented out that Console.WriteLine line and it still happens (of
>course).
>When I commented out the single. patcher.Patch() just above, it returns
>to command line after execution (without patching of course).
>
>Something in the OxidePatcher code causes it command line version to
>not exist and return to command prompt.
>
>Thanks for any help.

The problem stems from the fact that it is a Windows Forms application. The form must be initialized, even in CLI mode, so any code that creates dialogs will still do so. Making it run in pseudo CLI mode was basically a hack that I added way back. Making it run in true CLI mode would require a lot of the code to be copied or rewritten. I haven't worked on the project in a long time, but I'll have a look in the near future if I get the time.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by generationtech** [comment]
OK, that makes sense. I've reviewed the code in depth before asking on this old thread, so I can clearly see where the form and non-form parts are. Actually it appears all of the mechanics of reading the *.obj and acting upon patched dlls does not really require window forms at all; the logic seems nicely disconnected. I suppose I could work on finding a way to make the command version work.

**Comment by HellUnit** [comment]
On July 6, 2017 10:29:39 PM EDT, Ken McDonald <notifications@github.com> wrote:
>OK, that makes sense. I've reviewed the code in depth before asking on
>this old thread, so I can clearly see where the form and non-form parts
>are. Actually it appears all of the mechanics of reading the *.obj and
>acting upon patched dlls does not really require window forms at all;
>the logic seems nicely disconnected. I suppose I could work on finding
>a way to make the command version work.

I remember that I went through and changed some of the code to differentiate between when it was run in console mode or not (i.e. the 'isConsole' variable, I think). Since the weekend is coming up, I was going to have you elaborate more on the specific problem and have you tell me which dll you were trying to patch with a copy of the opj as well so I could poke around. But you're more than welcome to explore on your own and share the results. :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by generationtech** [comment]
A bit more info about the behavior. If I run the command line patcher from inside a command prompt, it waits for press-enter. If I put it into a *.cmd file with the same command line options, and run from command line, it waits for press-enter. But, if I use Windows Explorer and double-click the *.cmd file it runs to completion and exists.

For the *.cmd use, I was able to get that to close normally as expected when ran from the command line or called from another *.cmd file by using a syntax like:

`OxidePatcher.exe -c Rust.opj && exit`

**Comment by HellUnit** [comment]
IIRC, I think the wait is so the user can read any error messages generated before the console closes. Otherwise, they'd never be seen since they're all printed to the console. Gonna take a look at the code here in a bit. May be able to add a switch to exit immediately if no exceptions are generated, so it would only wait if an exception was thrown.

**Comment by HellUnit** [comment]
After reading over the older posts, now I remember what the issue was. I never could find a way to force the console window to close. The various methods of trying to force an exit didn't work. I added the "Press Enter to continue" message to prompt the user for action since it won't exit on its own for some reason. If using a cmd script with an exit command creates the behavior you need, I would go with that solution.
